### ISSUE TITLE
[功能] 自定义分词器，支持输入无效字符后自动过滤

### ISSUE THREAD

**Issue by orangelckc** [cuixueshe/earthworm#577]
### Description

RT，可以作为自动纠错模式选项，提供给用户

> FIX：#281 以及其他因为分词算法导致的数据错乱

## 目前的样子
会100%原样保存用户输入的结果
![image](https://github.com/cuixueshe/earthworm/assets/48410934/0e1932f2-3c72-4698-885a-7c241e0c9df0)

## 期望
在用户输入无效字符时自动过滤，不显示
![image](https://github.com/cuixueshe/earthworm/assets/48410934/d2769853-33ca-401f-996f-ac3463c0e366)

## TASK

- [ ] 重构当前以“空格”分词的逻辑，抽离分词逻辑
- [ ] 适配高亮处理逻辑
- [ ] 添加对于无效字符的测试用例
- [ ] 添加【纠错模式】选项
- [ ] 适配【纠错模式】不同状态的分词逻辑

**Comment by cuixiaorui** [comment]
在输入交互上 earthworm 的逻辑是尽可能的保持和真实场景下写出一个句子的动作保持一致
这是为了形成正确的肌肉记忆
所以当输入错误的时候 就应该让用户主动去删除
系统不应该做过多复杂的处理
