### ISSUE TITLE
[重构] - 前端现有逻辑

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/earthworm#72]
针对于现有代码做以下重构
保证代码的可读性以及后续的可扩展性&可维护性

## todos
- [ ] 新增用户和游客两个概念
- [ ] 封装 router 相关的逻辑
       - 目前关于路由的跳转都是基于写死的 path string
       - 不好维护以及不便于复用
- [ ] questionInput 的单元测试需要使用 component test 来重构
- [x] 目录结构的调整
	- 需要迁移
		- drizzle
		- libs
		- scripts/course
	- 目标
		- apps
		- packages
- [x] 关闭 auto import

> 后续想到哪些重构点 都可以加在这里

**Comment by liudewa888** [comment]
确实没必要强制登录(会阻止一部分新人),不想参与排名的,以游客身份进行练习,体验好了,自然会登录的

**Comment by cuixiaorui** [comment]
<img width="713" alt="image" src="https://github.com/cuixueshe/earthworm/assets/12064746/dfdb8426-372c-492b-9377-7da8754a6d14">

questionInput 中不可以出现 summer ， 职责不单一
可以让 summer 组件内部 watch course isDone 来决定是否弹出来

**Comment by dowithless** [comment]
建议：组件使用显示导入的方式，而不是使用全局/隐式导入

我所遇到的问题：
我想查看game的核心逻辑（如：键入内容后是如何检查答案是否正确，如何跳转下一题？）
然后根据文件名称找到了以下代码：
`apps\client\pages\game\[coursePackId]\[id].vue`
```vue
<template>
  <div class="flex w-full flex-col pt-2">
    <template v-if="isLoading">
      <Loading></Loading>
    </template>
    <template v-else>
      <MainTool />
      <MainGame />
    </template>
  </div>
</template>
```

根据组件名称可以猜测关键组件应该是 MainGame 
可是我在当前文件无法找到 MainGame 组件是在哪里定义的，我尝试全局搜索 MainGame 和 main-game 也没搜索到相关内容。
然后我猜测 MainGame 可能是注册成为了全局组件，于是查看了 app.vue ，然而还是没有发现相关线索。

我现在就很困扰，这个 MainGame 是在哪里实现的？
如果 MainGame 是在当前文件显示导入的，那么想查看该组件的实现就可以很容易定位到组件文件。
